Repository PROMAplatform/Proma_front, pull requests merged in 2024-07, with the labels that each got.

#4 ✨ Feature - SideBar UI, Singleton 을 위한 Axios, RecoilState 초기 세팅
  package-lock.json
  package.json
  src/api/community/community.js
  src/api/instance.js
  src/api/request.js
  src/api/user/user.js
  src/components/SideBar/SideBar.jsx
  src/components/SideBar/SideBar.module.css
  src/components/SideBar/Toggle.jsx
  src/components/SideBar/components/Chat/ChattingList.jsx
  src/components/SideBar/components/Chat/ChattingListItem.jsx
  src/components/SideBar/components/Chat/ChattingListItme.module.css
  src/components/SideBar/components/Prompt/PromptList.jsx
  src/components/SideBar/components/Prompt/PromptList.module.css
  src/components/SideBar/components/Prompt/PromptListItem.jsx
  src/components/SideBar/components/Prompt/PromptListItem.module.css
  src/components/common/CustomIconButton.jsx
  src/components/common/EmojiPickerButton.jsx
  src/hooks/useEmojiPicker.jsx
  src/hooks/useIconClick.jsx
  src/pages/mainPage.jsx
  src/recoil/community/communityRecoilState.js
  src/recoil/user/userRecoilState.js
Labels: ✨ feature

#7 ✨ Feature - community, mypage UI
  src/App.js
  src/assets/images/PromptPreview.svg
  src/assets/images/comlogo1.svg
  src/assets/images/comlogo2.svg
  src/assets/images/likeButton.svg
  src/assets/images/typeIcon.svg
  src/assets/images/writeIcon.svg
  src/components/Header/Header.jsx
  src/components/Header/Header.module.css
  src/components/Header/expandableButton/ExpandableButton.jsx
  src/components/Header/expandableButton/ExpandableButton.module.css
  src/components/community/FilterSection.jsx
  src/components/community/FilterSection.module.css
  src/components/community/Prompt/ComPromptListItem.jsx
  src/components/community/Prompt/ComPromptListItem.module.css
  src/components/community/Prompt/SharePromptList.jsx
  src/components/community/Prompt/SharePromptList.module.css
  src/components/community/mypage/LikePromptList.jsx
  src/components/community/mypage/WritePromptList.jsx
  src/components/community/mypage/filterSection/MyFilterSection.jsx
  src/components/community/mypage/filterSection/MyFilterSection.module.css
  src/pages/communityPage.jsx
  src/pages/communityPage.module.css
  src/pages/myPage.jsx
  src/pages/myPage.module.css
Labels: ✨ feature

#9 ✨ Feature - Prompt Making Page 초기 UI 및 일부 기능 구현
  package-lock.json
  package.json
  src/App.js
  src/assets/font/Inter-VariableFont_slnt,wght.ttf
  src/assets/font/MavenPro-Black.ttf
  src/assets/font/MavenPro-Bold.ttf
  src/assets/font/MavenPro-Medium.ttf
  src/assets/font/MavenPro-Regular.ttf
  src/assets/logos/Sidebar_Header.png
  src/components/Login/KakaoLogin.jsx
  src/components/Login/KakaoLoginAfter.jsx
  src/components/PromptMaking/CombinationArea.jsx
  src/components/PromptMaking/CombinationArea.module.css
  src/components/PromptMaking/FinalPromptArea.jsx
  src/components/PromptMaking/FinalPromptArea.module.css
  src/components/PromptMaking/PromptMakingSideBar.jsx
  src/components/PromptMaking/PromptMakingSidebar.module.css
  src/components/SideBar/SideBar.jsx
  src/components/common/CustomIconButton.jsx
  src/components/common/EmojiPickerButton.jsx
  src/hooks/common/useEmojiPicker.jsx
  src/hooks/common/useGlobalShortCut.jsx
  src/hooks/common/useIconClick.jsx
  src/hooks/common/useInput.jsx
  src/hooks/promptHook/usePromptMaking.jsx
  src/index.js
  src/pages/mainPage.jsx
  src/pages/promptMakingPage.jsx
  src/pages/promptMakingPage.module.css
  src/recoil/prompt/promptRecoilState.js
  src/recoil/util/utilRecoilState.js
  src/styles/global.css
Labels: ✨ feature

#10 ✨ Feature - 프롬프트 저장 모달 및 블럭 생성 모달 구현
  src/components/PromptMaking/CombinationArea/CombinationArea.jsx
  src/components/PromptMaking/CombinationArea/CombinationArea.module.css
  src/components/PromptMaking/CombinationArea/SavePromptModal.jsx
  src/components/PromptMaking/CombinationArea/SavePromptModal.module.css
  src/components/PromptMaking/FinalPromptArea.jsx
  src/components/PromptMaking/FinalPromptArea/FinalPromptArea.jsx
  src/components/PromptMaking/FinalPromptArea/FinalPromptArea.module.css
  src/components/PromptMaking/FinalPromptArea/RefinedPromptText.jsx
  src/components/PromptMaking/FinalPromptArea/RefinedPromptText.module.css
  src/components/PromptMaking/PromptMakingSideBar/CreateBlockModal.jsx
  src/components/PromptMaking/PromptMakingSideBar/CreateBlockModal.module.css
  src/components/PromptMaking/PromptMakingSideBar/PromptMakingSideBar.jsx
  src/components/PromptMaking/PromptMakingSideBar/PromptMakingSidebar.module.css
  src/pages/promptMakingPage.jsx
Labels: ✨ feature

#11 🎨 Refactoring - 프롬프트 제작 훅 및 PromptRecoil 상태 리팩토링
  src/components/PromptMaking/CombinationArea/CombinationArea.jsx
  src/components/PromptMaking/PromptMakingSideBar/CreateBlockModal.jsx
  src/components/PromptMaking/PromptMakingSideBar/PromptMakingSideBar.jsx
  src/hooks/promptHook/usePromptMaking.jsx
  src/recoil/prompt/promptRecoilState.js
Labels: 🎨 refactor

#13 ✨ Feature - 커뮤니티, MyPage 필요 모달 구현 및 기능 구현
  package-lock.json
  package.json
  src/assets/images/likeImg.svg
  src/assets/images/writePromptListIcon.svg
  src/components/Header/Header.jsx
  src/components/Header/expandableButton/ExpandableButton.jsx
  src/components/community/FilterSection.jsx
  src/components/community/Prompt/ComPromptListItem.jsx
  src/components/community/Prompt/SharePromptList.jsx
  src/components/community/mypage/LikePromptList.jsx
  src/components/community/mypage/WritePromptList.jsx
  src/components/community/mypage/filterSection/MyFilterSection.jsx
  src/components/sharingPrompt/Prompt/ComPromptListItem.jsx
  src/components/sharingPrompt/Prompt/ComPromptListItem.module.css
  src/components/sharingPrompt/Prompt/SharePromptList.jsx
  src/components/sharingPrompt/Prompt/SharePromptList.module.css
  src/components/sharingPrompt/community/FilterSection.jsx
  src/components/sharingPrompt/community/FilterSection.module.css
  src/components/sharingPrompt/components/FilterComponents/CategoryButton.jsx
  src/components/sharingPrompt/components/FilterComponents/CategoryButton.module.css
  src/components/sharingPrompt/components/FilterComponents/SortButton.jsx
  src/components/sharingPrompt/components/FilterComponents/SortButton.module.css
  src/components/sharingPrompt/modal/DeleteModal/DeletePromptModal.jsx
  src/components/sharingPrompt/modal/DeleteModal/DeletePromptModal.module.css
  src/components/sharingPrompt/modal/DetailModal/PromptDetailModal.jsx
  src/components/sharingPrompt/modal/DetailModal/PromptDetailModal.module.css
  src/components/sharingPrompt/modal/DetailModal/components/ButtonSection.jsx
  src/components/sharingPrompt/modal/DetailModal/components/ButtonSection.module.css
  src/components/sharingPrompt/modal/DetailModal/components/TopSection.jsx
  src/components/sharingPrompt/modal/DetailModal/components/TopSection.module.css
  src/components/sharingPrompt/modal/FixAndShareModal/PostFixOrShare.jsx
  src/components/sharingPrompt/modal/FixAndShareModal/PostFixOrShare.module.css
  src/components/sharingPrompt/modal/SelectModal/SelectPromptModal.jsx
  src/components/sharingPrompt/modal/SelectModal/SelectPromptModal.module.css
  src/components/sharingPrompt/modal/SelectModal/components/PromptListName.jsx
  src/components/sharingPrompt/modal/SelectModal/components/PromptListName.module.css
  src/components/sharingPrompt/modal/SelectModal/components/ShareSection.jsx
  src/components/sharingPrompt/modal/SelectModal/components/ShareSection.module.css
  src/components/sharingPrompt/modal/components/MakeBlockPreview.jsx
  src/components/sharingPrompt/modal/components/MakeBlockPreview.module.css
  src/components/sharingPrompt/mypage/filterSection/MyFilterSection.jsx
  src/components/sharingPrompt/mypage/filterSection/MyFilterSection.module.css
  src/hooks/useModal.jsx
  src/pages/communityPage.jsx
  src/pages/myPage.jsx
  src/recoil/community/communityRecoilState.js
  src/recoil/community/myPageRecoilState.js
Labels: ✨ feature, 🎨 refactor
