Repository PROMAplatform/Proma_front, pull requests merged in 2024-08, with the labels that each got.

#18 ✨ Feature - 채팅방, 채팅 리스트, 프롬프트 제작 관련 함수 API 일부 구현
  package-lock.json
  src/api/chatting/chatting.js
  src/api/chatting/chattingRoomAPI.js
  src/api/instance.js
  src/api/prompt/prompt.js
  src/api/request.js
  src/components/Chatting/Chatting.jsx
  src/components/Chatting/components/input/ChattingInput.jsx
  src/components/SideBar/SideBar.jsx
  src/components/SideBar/components/Chat/ChattingList.jsx
  src/components/SideBar/components/Chat/ChattingListItem.jsx
  src/components/SideBar/components/Prompt/PromptList.jsx
  src/components/SideBar/components/Prompt/PromptListItem.jsx
  src/components/common/EmojiPickerButton.jsx
  src/hooks/common/useEmojiPicker.jsx
  src/recoil/prompt/promptRecoilState.js
Labels: ✨ feature, 🐛 fix

#20 ✨ Feature - 채팅방, 채팅 리스트, 프롬프트 제작 관련 함수 API 일부 구현 -2
  .github/workflows/front-build.yaml
  .gitignore
  src/api/chatting/chatting.js
  src/api/instance.js
  src/api/prompt/prompt.js
  src/components/Chatting/components/ChattingMain.jsx
  src/components/Chatting/components/Prompt/PromptCreateButton.jsx
  src/components/PromptMaking/CombinationArea/CombinationArea.jsx
  src/components/PromptMaking/CombinationArea/SavePromptModal.jsx
  src/components/PromptMaking/PromptMakingSideBar/CreateBlockModal.jsx
  src/components/PromptMaking/PromptMakingSideBar/PromptMakingSideBar.jsx
  src/components/SideBar/SideBar.jsx
  src/components/SideBar/components/Chat/ChattingList.jsx
  src/components/SideBar/components/Chat/ChattingListItem.jsx
  src/components/SideBar/components/Prompt/PromptList.jsx
  src/components/SideBar/components/Prompt/PromptListItem.jsx
  src/components/common/EmojiPickerButton.jsx
  src/pages/mainPage.jsx
  src/recoil/prompt/promptRecoilState.js
Labels: ✨ feature, 🐛 fix

#22 ✨ Feature - 채팅방, 채팅 리스트, 프롬프트 제작 관련 함수 API 일부 구현 -3
  src/App.js
  src/api/chatting/chatting.js
  src/api/instance.js
  src/components/Chatting/components/Messages/ChattingMessages.jsx
  src/components/Chatting/components/Prompt/PromptPreview.jsx
  src/components/Chatting/components/input/ChattingInput.jsx
  src/components/PromptMaking/CombinationArea/SavePromptModal.jsx
  src/components/SideBar/components/Prompt/PromptListItem.jsx
  src/components/SideBar/components/Toggle.jsx
  src/hooks/common/useGlobalShortCut.jsx
  src/recoil/prompt/promptRecoilState.js
Labels: ✨ feature, 🎨 refactor

#26 🎨 Refactor - Sidebar Style Refactoring
  src/components/SideBar/components/Chat/ChattingList.jsx
  src/components/SideBar/components/Prompt/Modal/CreatePromptModal.jsx
  src/components/SideBar/components/Prompt/Modal/CreatePromptModal.module.css
  src/components/SideBar/components/Prompt/Modal/DeletePromptModal.jsx
  src/components/SideBar/components/Prompt/Modal/DeletePromptModal.module.css
  src/components/SideBar/components/Prompt/MoreButton.jsx
  src/components/SideBar/components/Prompt/MoreButton.module.css
  src/components/SideBar/components/Prompt/PromptList.jsx
  src/components/SideBar/components/Prompt/PromptMethodButton.jsx
  src/components/SideBar/components/Prompt/PromptMethodButton.module.css
  src/components/SideBar/components/SkeletonListItem.jsx
  src/components/SideBar/components/SkeletonListItem.module.css
  src/components/common/Prompt/PromptDetail.jsx
Labels: 🎨 refactor

#27 ✨ Feature - Sidebar 프롬프트 공유 api 연결 및 에러 수정
  src/api/prompt/prompt.js
  src/components/PromptMaking/CombinationArea/SavePromptModal.jsx
  src/components/SideBar/components/Prompt/Modal/SharePromptModal.jsx
  src/components/common/Prompt/PromptCategoryBlock.jsx
  src/components/common/Prompt/PromptDetail.jsx
  src/components/common/Prompt/PromptValueBlock.jsx
  src/recoil/prompt/promptRecoilState.js
Labels: ✨ feature, 🐛 fix

#31 🐛 Fix - 프롬프트 블록 수정 에러 해결
  src/components/Chatting/components/ChattingInput/ChattingInput.module.css
  src/components/PromptMaking/CombinationArea/SavePromptModal.jsx
  src/components/PromptMaking/PromptMakingSideBar/CreateBlockModal.jsx
  src/components/PromptMaking/PromptMakingSideBar/CreateBlockModal.module.css
  src/hooks/promptHook/usePromptMaking.jsx
  src/pages/aboutPage.module.css
Labels: 🐛 fix

#32 🐛 Fix - CreatePromptModal에서 promptMethod 설정 추가하기
  src/api/chatting/chatting.js
  src/components/SideBar/components/Prompt/Modal/CreatePromptModal.jsx
Labels: 🐛 fix

#34 ✨ Feature - community auth feat
  src/App.js
  src/api/community/community.js
  src/api/community/myPage.js
  src/components/Header/Header.jsx
  src/components/Header/expandableButton/ExpandableButton.jsx
  src/components/SharingPrompt/community/FilterSection.jsx
  src/components/SharingPrompt/modal/DetailModal/components/ButtonSection.jsx
  src/components/SharingPrompt/modal/DetailModal/components/TopSection.jsx
Labels: ✨ feature

#35 🐛 Fix - community auth 수정, header css 수정
  src/api/community/community.js
  src/api/community/myPage.js
  src/components/Header/expandableButton/ExpandableButton.jsx
  src/components/Header/expandableButton/ExpandableButton.module.css
Labels: 🐛 fix

#36 🐛 Fix - community css 수정, header css 수정
  src/components/Header/expandableButton/ExpandableButton.jsx
  src/components/SharingPrompt/modal/DetailModal/PromptDetailModal.jsx
  src/components/SharingPrompt/modal/FixAndShareModal/PostFixOrShare.jsx
  src/components/SharingPrompt/modal/SelectModal/SelectPromptModal.jsx
  src/components/SharingPrompt/modal/SelectModal/components/ShareSection.jsx
  src/locales/en/translation.json
  src/locales/ko/translation.json
Labels: 🐛 fix

#37 💄 style: 모달창 다국어 지원
  src/components/SharingPrompt/Prompt/ComPromptListItem.jsx
  src/components/SharingPrompt/modal/DeleteModal/DeletePromptModal.jsx
  src/components/SharingPrompt/modal/DetailModal/PromptDetailModal.jsx
  src/components/SharingPrompt/modal/DetailModal/components/ButtonSection.jsx
  src/components/SharingPrompt/modal/FixAndShareModal/PostFixOrShare.jsx
  src/components/SideBar/components/Prompt/Modal/DeletePromptModal.jsx
  src/components/SideBar/components/Prompt/Modal/EditPromptInfoModal.jsx
  src/components/SideBar/components/Prompt/Modal/SharePromptModal.jsx
  src/locales/en/translation.json
  src/locales/ko/translation.json
Labels: ✨ feature

#39 🐛 Fix - patch modal detail 수정
  src/components/SharingPrompt/modal/DetailModal/PromptDetailModal.jsx
  src/components/SharingPrompt/modal/DetailModal/components/ButtonSection.jsx
Labels: 🐛 fix

#41 💄 Style - community scroll css 수정
  src/components/SharingPrompt/Prompt/ComPromptListItem.module.css
Labels: 🐛 fix

#43 🚑 fix: community card 줄바꿈 예외 처리
  src/components/SharingPrompt/Prompt/ComPromptListItem.jsx
  src/components/SharingPrompt/Prompt/ComPromptListItem.module.css
  src/components/SharingPrompt/modal/DetailModal/PromptDetailModal.jsx
  src/components/SharingPrompt/modal/DetailModal/PromptDetailModal.module.css
Labels: 🐛 fix

#44 🚑 fix: community modal 줄바꿈 예외 처리
  src/components/PromptMaking/CombinationArea/SavePromptModal.module.css
  src/components/SharingPrompt/modal/FixAndShareModal/PostFixOrShare.jsx
  src/components/SharingPrompt/modal/FixAndShareModal/PostFixOrShare.module.css
  src/components/SideBar/components/Chat/ChattingList.module.css
  src/components/SideBar/components/Prompt/PromptList.module.css
Labels: 🚑 hot fix

#47 ✨ Feature - community list api method params 추가
  src/api/community/community.js
  src/components/SharingPrompt/community/FilterSection.jsx
Labels: ✨ feature, 🚑 hot fix

#50 💄 Style - 채팅방 메시지 잘림 문제 해결
  src/components/Chatting/components/Messages/ChattingMessages.module.css
Labels: 🐛 fix
