Repository PROMAplatform/Proma_front, pull requests merged in 2024-10, with the labels that each got.

#56 💄 Style - 모바일 반응형 Intro 및 헤더 적용
  package-lock.json
  package.json
  src/assets/images/koreaFlag.jpg
  src/assets/images/usaFlag.svg
  src/components/Header/Header.jsx
  src/components/Header/Header.module.css
  src/components/Header/expandableButton/ExpandableButton.jsx
  src/components/Header/expandableButton/ExpandableButton.module.css
  src/components/common/MobileMessage.jsx
  src/components/common/MobileMessage.module.css
  src/hooks/common/useScreenSize.jsx
  src/pages/aboutPage.jsx
  src/pages/aboutPage.module.css
  src/pages/communityPage.jsx
  src/pages/mainPage.jsx
  src/pages/mainPage.module.css
  src/pages/myPage.jsx
  src/pages/promptMakingPage.jsx
Labels: ✨ feature, 🐛 fix, 🎨 refactor

#59 🎨 Refactoring - FE refactoring and css 일부 수정
  src/api/community/community.js
  src/components/SharingPrompt/FilterSection/FilterSection.jsx
  src/components/SharingPrompt/FilterSection/FilterSection.module.css
  src/components/SharingPrompt/FilterSection/MyFilterSection.jsx
  src/components/SharingPrompt/FilterSection/components/CategoryButton.jsx
  src/components/SharingPrompt/FilterSection/modal/SelectModal/SelectPromptModal.module.css
  src/components/SharingPrompt/FilterSection/modal/SelectModal/components/PromptListName.module.css
  src/components/SharingPrompt/FilterSection/modal/SelectModal/components/ShareSection.jsx
  src/components/SharingPrompt/FilterSection/modal/SelectModal/components/ShareSection.module.css
  src/components/SharingPrompt/Prompt/ComPromptListItem.jsx
  src/components/SharingPrompt/Prompt/ComPromptListItem.module.css
  src/components/SharingPrompt/Prompt/SharePromptList.jsx
  src/components/SharingPrompt/Prompt/SharePromptList.module.css
  src/components/SharingPrompt/Prompt/modal/DeleteModal/DeletePromptModal.module.css
  src/components/SharingPrompt/Prompt/modal/DetailModal/PromptDetailModal.jsx
  src/components/SharingPrompt/Prompt/modal/DetailModal/PromptDetailModal.module.css
  src/components/SharingPrompt/Prompt/modal/DetailModal/components/ButtonSection.jsx
  src/components/SharingPrompt/Prompt/modal/DetailModal/components/ButtonSection.module.css
  src/components/SharingPrompt/Prompt/modal/FixAndShareModal/PostFixOrShare.module.css
  src/components/SharingPrompt/util/categoryImage.js
Labels: ❗bug, 🎨 refactor

#62 ✨ Feature - 채팅방 프롬프트 적용 기능 + s3 버그 해결
  src/components/Chatting/components/Messages/ChattingMessages.jsx
  src/components/Chatting/components/Prompt/PromptPreview.jsx
  src/components/Chatting/components/Prompt/PromptPreview.module.css
  src/util/randomString.js
  src/util/s3Upload.js
Labels: ✨ feature, 🐛 fix

#71 ✨Feature - Open API 페이지 구현
  src/App.js
  src/api/business/openAPI.js
  src/api/instance.js
  src/assets/images/codeIcon.svg
  src/assets/images/logIcon.svg
  src/assets/images/openapiStep/openapiStepBig1.svg
  src/assets/images/openapiStep/openapiStepBig2.svg
  src/assets/images/openapiStep/openapiStepBig3.svg
  src/assets/images/openapiStep/openapiStepBig4.svg
  src/assets/images/openapiStep/openapiStepBig5.svg
  src/assets/images/openapiStep/openapiStepBig6.svg
  src/components/Chatting/Chatting.module.css
  src/components/Chatting/components/Messages/SkeletonMessage.module.css
  src/components/Header/Header.jsx
  src/components/Header/Header.module.css
  src/components/Header/expandableButton/AboutExpandableButton.jsx
  src/components/Header/expandableButton/ExpandableButton.module.css
  src/components/OpenAPI/OpenAPI/PromaAPIInfo.jsx
  src/components/OpenAPI/OpenAPI/PromaAPIInfo.module.css
  src/components/OpenAPI/OpenAPI/PromaAPIList.jsx
  src/components/OpenAPI/OpenAPI/PromaAPIList.module.css
  src/components/OpenAPI/OpenAPI/PromptDetailTable.jsx
  src/components/OpenAPI/OpenAPI/PromptDetailTable.module.css
  src/components/OpenAPI/OpenAPI/components/CopyButton.jsx
  src/components/OpenAPI/OpenAPI/components/CopyButton.module.css
  src/components/OpenAPI/OpenAPI/modal/PromptDetailModal.jsx
  src/components/OpenAPI/OpenAPI/modal/PromptDetailModal.module.css
  src/components/OpenAPI/OpenAPI/modal/PromptListModal.jsx
  src/components/OpenAPI/OpenAPI/modal/PromptListModal.module.css
  src/components/OpenAPI/OpenAPI/modal/components/PromptListItem.jsx
  src/components/OpenAPI/OpenAPI/modal/components/PromptListItem.module.css
  src/components/OpenAPI/OpenAPIDocs/PromaAPIDocs.jsx
  src/components/OpenAPI/OpenAPIDocs/PromaAPIDocs.module.css
  src/components/OpenAPI/OpenAPIDocs/components/APISpecification.jsx
  src/components/OpenAPI/OpenAPIDocs/components/APISpecification.module.css
  src/components/OpenAPI/OpenAPIDocs/components/UseGuide.jsx
  src/components/OpenAPI/OpenAPIDocs/components/UseGuide.module.css
  src/components/OpenAPI/components/SquareButton.jsx
  src/components/OpenAPI/components/SquareButton.module.css
  src/components/SharingPrompt/Prompt/SharePromptList.jsx
  src/components/SideBar/components/Prompt/PromptList.jsx
  src/components/SideBar/components/Prompt/PromptMethodButton.jsx
  src/components/SideBar/components/Prompt/PromptMethodButton.module.css
  src/components/common/ModalContainer.jsx
  src/components/common/NavigateButton.jsx
  src/locales/en/translation.json
  src/locales/ko/translation.json
  src/pages/OpenAPIDocsPage.jsx
  src/pages/OpenAPIDocsPage.module.css
  src/pages/aboutOpenAPIPage.jsx
  src/pages/aboutOpenAPIPage.module.css
  src/pages/aboutPage.module.css
  src/pages/mainPage.module.css
  src/pages/openAPIPage.jsx
  src/pages/openAPIPage.module.css
  src/recoil/openapi/openapiState.js
Labels: ✨ feature
